# This Dockerfile is for Odoo 13 with python 3.6
FROM ubuntu:18.04

RUN set -ex \
  && apt-get update \
  && apt-get -y install \
    git \
    python3-venv \
  && rm -rf /var/lib/apt/lists/*

# TODO install other common apt packages for OCA

# TODO install wkhtmltopdf

RUN git clone --depth=1 --branch=13.0 https://github.com/odoo/odoo /opt/odoo-src

ENV PIP_USE_FEATURE 2020-resolver
ENV PIP_NO_CACHEDIR=1

# TODO remove dependency on https://wheelhouse.acsone.eu/manylinux1 by pre-installing build deps
RUN set -ex \
  && python3 -m venv /opt/odoo-venv \
  && /opt/odoo-venv/bin/pip install -U pip wheel setuptools \
  && /opt/odoo-venv/bin/pip install -r /opt/odoo-src/requirements.txt -e /opt/odoo-src -f https://wheelhouse.acsone.eu/manylinux1 \
  && /opt/odoo-venv/bin/pip install -U coverage websocket-client

# TODO remove dependency on acsoo by moving 'acsoo addons' to a standalone project
RUN set -ex \
  && python3 -m venv /opt/acsoo-venv \
  && /opt/acsoo-venv/bin/pip install -U pip wheel setuptools \
  && /opt/acsoo-venv/bin/pip install acsoo
COPY addons /usr/local/bin

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENV PATH=/opt/odoo-venv/bin:$PATH
